sentry:
  image: sentry:8-onbuild
  command: sentry --config=/etc/sentry.conf.py start
  links:
    - redis
    - postgres
  ports:
    - "9000:9000"
  volumes:
    - /docker-data/sentry/:/data/
  environment:
    - POSTGRES_PASSWORD
    - SENTRY_SECRET_KEY
    - SENTRY_EMAIL_HOST
    - SENTRY_EMAIL_PORT
    - SENTRY_SERVER_EMAIL
redis:
  image: redis
  ports:
    - "6379:6379"
postgres:
  image: postgres
  environment:
    - POSTGRES_PASSWORD
worker:
  image: sentry:8-onbuild
  command: sentry celery worker
  links:
    - redis
    - postgres
  environment:
    - CELERY_BROKER_URL=redis://redis
    - POSTGRES_PASSWORD
    - SENTRY_SECRET_KEY
beat:
  image: sentry:8-onbuild
  command: sentry celery beat
  links:
    - redis
    - postgres
  environment:
    - CELERY_BROKER_URL=redis://redis
    - POSTGRES_PASSWORD
    - SENTRY_SECRET_KEY
